## Given a list lst perform elementwise addition with 5.

In [8]:
# Input
lst = [5, 10, 0, 200]

import numpy as np
arr= np.array(lst)
print(arr + 5)

[ 10  15   5 205]


## Given a list lst do a homogeneity test on each element. 

In [11]:
lst = [1, 2, 3, 'text', True, 3+2j] 

import numpy as np
arr=np.array(lst)

print(type(arr[0]),type(arr[4]),type(arr[5]))

<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>


## Given a list lst find its complete size in bytes. Hint: use sys.getsizeof(lst)

In [12]:
lst = [56, 45, 12, 6]
import numpy as np
arr = np.array(lst)
print(arr.nbytes)

16


## Creation of Numpy Object

In [14]:
print(np.array([5,6,7,2,45,3,2,1]).reshape(2,4))

[[ 5  6  7  2]
 [45  3  2  1]]


In [15]:
print(np.arange(0,10,1,dtype=np.float64))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [16]:
print(np.linspace(0,100,5,dtype=np.float64))

[  0.  25.  50.  75. 100.]


In [18]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
arr = np.ones(3, dtype=np.float32)
print(arr)

[1. 1. 1.]


In [24]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


## Given two NumPy arrays arr1 = [25, 56, 12, 85, 34, 75] and arr2 = [42, 3, 86, 32, 856, 46], solve the following:

## 1.Create a new NumPy array Narr with the shape equal to arr1 filled with random values.

## 2. Permanently change the dtype of arr1 to complex.

## 3.Transform arrays arr1 and arr2 into two matrices (arr1_mat and arr2_mat) of shape (2,3) and arrive at the solution of the following equation:



In [32]:
arr1 = np.array([25, 56, 12, 85, 34, 75] )
arr2 = np.array([42, 3, 86, 32, 856, 46])

#Q1
narr = np.random.rand(len(arr1))
print(narr)

[0.83132663 0.17875164 0.32049219 0.0296935  0.24651598 0.0887764 ]


Q2 - TWO METHODS

In [35]:
arr1=np.array(arr1,dtype='complex')
print(arr1)

[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


In [34]:
arr1 = arr1.astype("complex")
print(arr1)

[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


In [39]:
#Q3
arr1_mat=arr1.reshape(2,3)
arr2_mat =arr2.reshape(2,3)

print(arr1_mat)
print(arr2_mat)

[[25.+0.j 56.+0.j 12.+0.j]
 [85.+0.j 34.+0.j 75.+0.j]]
[[ 42   3  86]
 [ 32 856  46]]


In [46]:
#Q4

#Calculate (arr1_mat^2 - arr2_mat^2) / (arr1_mat - arr2_mat)
# solution = (arr1_mat**2 - arr2_mat**2) / (arr1_mat - arr2_mat)
# Calculate (arr1_mat^2 - arr2_mat^2) / (arr1_mat - arr2_mat) using the square function

solution= (np.square(arr1_mat)-np.square(arr2_mat))/(arr1_mat - arr2_mat)
print(solution)



[[ 67.-0.j  59.+0.j  98.-0.j]
 [117.+0.j 890.-0.j 121.+0.j]]


In [48]:
import numpy as np
arr = np.arange(4)
arr.reshape(2,2)
print(arr.shape)

#arr.reshape craetes a new array ,that is original array remains the same so the shape is 4 itself

(4,)


In [49]:
import numpy as np
arr = np.arange(4).reshape(4,-1)
print(arr.shape)

(4, 1)


In [50]:
import numpy as np

arr1 = np.ones(10)
arr2 = np.arange(10, dtype = np.float64)
arr3 = arr1 + arr2
print(np.result_type(arr1))
print(np.result_type(arr3))
 

float64
float64


## Create a 4 x 4 matrix and add values 4,5,6 above the parent diagonal.

In [64]:
import numpy as np

# Create a 4x4 matrix with zeros
matrix = np.zeros((4, 4))

# Values to place above the main diagonal
values = [4, 5, 6]

# Fill the values above the main diagonal
for i in range(len(values)):
    matrix[i, i+1] = values[i]

print(matrix)


#matrix[0,1] - Insert at first row second place (=values[0]=4 )
#matrix][1,2] - Insert at second row third place ie, 2nd index ( =values[1]=5 )
#matrix[2,3] - Insert at third row 4 th place  (= values[2] = 6 )



[[0. 4. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 6.]
 [0. 0. 0. 0.]]


## Given a Numpy array arr = np.arange(11), negate all the elements between 6 and 10


In [72]:
import numpy as np
arr = np.arange(11)

#BOOLEAN OPERATION STEP

print(arr > 6)


[False False False False False False False  True  True  True  True]


In [73]:
print (arr<=10)

[ True  True  True  True  True  True  True  True  True  True  True]


In [74]:
print(arr[(arr >6) & (arr<=10)])

[ 7  8  9 10]


In [68]:
import numpy as np

arr= np.arange(11)

arr[(arr > 6) & (arr<=10)] *= -1

print(arr)

[  0   1   2   3   4   5   6  -7  -8  -9 -10]


## Given a matrix mat and an array arr, for each row of the matrix if elements of Column 1 are equal to the corresponding element of the array, then print the corresponding value of Column 2 of the matrix.

In [75]:
import numpy as np
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 

for row in mat:
    if row[0] in arr:
        print(row[1])
 


A
C


## Given a matrix mat, sort it by the second column.

 


In [76]:
import numpy as np
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])

sorted = mat[mat[:,1].argsort()]

#mat[:,1] - : selects the all rows , 1 - selects the second column.

#argsort() - function in NumPy returns the indices that would sort an array.

print(sorted)

[[ 5  4  2]
 [56 12  4]
 [ 1 21  3]]


## Given an array arr, find the top 4 maximum values.

 

In [77]:
import numpy as np
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 5])

# Find the indices of the top 4 maximum values
top_indices = np.argsort(arr)[-4:]

# Select the top 4 maximum values using the indices
top_values = arr[top_indices]

# Sort the top values in descending order
top_values_sorted = np.sort(top_values)[::-1]

print("Top 4 maximum values:", top_values_sorted)


Top 4 maximum values: [590  90  45  24]


## Find the nearest number from the given number in an array.

 

In [80]:
import numpy as np

# Define the array and the target number
arr = np.array([10, 55, 22, 3, 6, 44, 9, 54])
nearest_to = 50

# Step 1: Compute the absolute differences
differences = np.abs(arr - nearest_to)
print("Differences:", differences)

# Step 2: Find the index of the minimum difference 
nearest_index = np.argmin(differences)
print("Index of nearest value:", nearest_index)

# Step 3: Use the index to get the nearest number
nearest_value = arr[nearest_index]
print("Nearest value to", nearest_to, "is", nearest_value)

Differences: [40  5 28 47 44  6 41  4]
Index of nearest value: 7
Nearest value to 50 is 54


## Given a matrix mat of size 3 x 3. Find the maximum numbers from each row, say N1, N2 and N3. Result in a matrix by adding:
 

N1 to the upper half elements of mat

N2 to the main diagonal elements of mat

N3 to the lower half elements of mat

In [2]:
import numpy as np
mat = np.array([[10,5,9],
                [2,20,6],
                [8,3,30]]).reshape(3,3)

#find the max element from each row

N1=np.max(mat[0,:])
N2=np.max(mat[1,:])
N3=np.max(mat[2,:])

# Create a copy of the matrix to store the result
result = mat.copy()

# Add N1 to the upper half elements (excluding the main diagonal)
upper_half_indices = np.triu_indices(3, k=1)
result[upper_half_indices] += N1

# Add N2 to the main diagonal elements
main_diagonal_indices = np.diag_indices(3)
result[main_diagonal_indices] += N2

# Add N3 to the lower half elements (excluding the main diagonal)
lower_half_indices = np.tril_indices(3, k=-1)
result[lower_half_indices] += N3

# Print the result
print(result)

[[30 15 19]
 [32 40 16]
 [38 33 50]]


Find the Maximum Numbers:

N1 = 10 (maximum of first row)
N2 = 20 (maximum of second row)
N3 = 30 (maximum of third row)
Upper Half Elements:

Indices: (0, 1), (0, 2), and (1, 2)
Add N1 = 10 to these elements
Main Diagonal Elements:

Indices: (0, 0), (1, 1), and (2, 2)
Add N2 = 20 to these elements
Lower Half Elements:

Indices: (1, 0) and (2, 0), (2, 1)
Add N3 = 30 to these elements

In [3]:
#Find the output of the following code:

arr = np.array([10,5,6,7]).reshape(2,-1)
print(arr.sum(axis = 0))

[16 12]


arr = np.array([10,5,6,7]).reshape(2,-1) creates a NumPy array with the values [10, 5, 6, 7] and reshapes it into a 2x2 matrix. The -1 in the reshape method tells NumPy to infer the correct number of columns based on the length of the array and the specified number of rows (2 in this case).

In [4]:
import numpy as np
arr = np.arange(9, dtype = "float").reshape(3,3)
ind1 = np.array([[1,2],[0,1]])
ind2 = np.array([[0,2],[1,2]])
print(arr[ind1, ind2].sum())

17.0


Create the NumPy array:

arr = np.arange(9, dtype="float").reshape(3, 3) creates a 3x3 NumPy array with elements from 0 to 8, reshaped into a 3x3 matrix.

 Indexing with ind1 and ind2:

ind1 and ind2 are arrays that specify the indices to select from arr.
When using advanced indexing like arr[ind1, ind2], it pairs the elements of ind1 and ind2 to select specific elements from arr.
 
 Sum the selected elements:

The sum of the elements selected by arr[ind1, ind2] is then computed.